// Content for the "Core concepts" guide (conceptsui.js): the ideas that come up in every system
// design whatever the technology. Five themes, each a handful of topics. A topic says what the idea
// is, what it gets you and costs you, and where this simulator shows it, if it does.
//
// General knowledge, written to be read next to the simulator. `sim` is null where the idea is
// not modelled here, and the guide says so.

export const THEMES = [
  {
    id: 'concurrency',
    name: 'Doing many things at once',
    intro: 'A server handles thousands of requests that overlap in time. Most hard bugs in a system come from two of them touching the same thing at the same moment.',
    topics: [
      {
        id: 'parallelism',
        title: 'Concurrency and parallelism',
        one: 'Concurrency is juggling many tasks; parallelism is doing several at the same instant.',
        what: [
          'A web request spends most of its life waiting: for the database, for another service, for the network. <b>Concurrency</b> means a server makes progress on many requests by switching between them while they wait, even on a single core. <b>Parallelism</b> means work really runs at the same moment on several cores. Serving requests is mostly a concurrency problem; resizing images is a parallelism one.',
          'How a server gets concurrency sets its limits. One <b>thread per request</b> is simple, but every waiting request holds a thread and its memory, so a slow dependency can pin all of them. An <b>event loop</b> handles thousands of waiting requests on one thread, as long as nothing blocks it.',
        ],
        pros: ['One machine serves far more requests than it has cores', 'Waiting time is not wasted time'],
        cons: ['Waiting requests still hold threads, memory and connections', 'Shared state now needs protecting from simultaneous use'],
        sim: 'Overload the OLTP database, then select an application server. Its status reads "Thread pool exhausted": all 256 threads are stuck waiting on the database while the CPU sits idle.',
      },
      {
        id: 'races',
        title: 'Race conditions',
        one: 'Two operations interleave, and the result depends on who got there first.',
        what: [
          'The classic case is <b>read, modify, write</b>. Two requests each read a stock count of 1, each decide the item is available, and each write back 0: two customers have bought the last one. Each request was correct on its own; the bug exists only in the overlap.',
          'Races are rare under light load and common under heavy load, which is why they survive testing and appear in production. The fixes all make the check and the change a single step: do it inside the database (<code>UPDATE … SET stock = stock - 1 WHERE stock > 0</code>), take a lock, or detect the conflict and retry.',
        ],
        pros: [],
        cons: ['Invisible in tests and in code review', 'Gets more frequent exactly as traffic grows', 'Corrupts data silently instead of failing loudly'],
        sim: null,
      },
      {
        id: 'locks',
        title: 'Locks and deadlock',
        one: 'Make others wait while you work. Simple, until two holders wait for each other.',
        what: [
          'A <b>lock</b> lets one request at a time into a critical section; everyone else queues. This is <b>pessimistic</b> concurrency control: it assumes a conflict will happen and pays the waiting cost every time. Inside one process it is a mutex; inside a database it is a row lock; across machines it is a <b>distributed lock</b> held in something like Redis or ZooKeeper, with a time limit so a crashed holder does not hold it for ever.',
          '<b>Deadlock</b> is two requests each holding a lock the other needs. Databases detect it and abort one. The usual prevention is to always take locks in the same order. Distributed locks have a subtler failure: a holder that pauses past its time limit still believes it holds the lock, so anything it guards must also reject stale holders.',
        ],
        pros: ['Easy to reason about: one at a time', 'The right tool when conflicts are frequent'],
        cons: ['Everyone else waits, so throughput drops', 'Deadlocks when locks are taken in different orders', 'A distributed lock can be held by two parties at once after a pause or a network split'],
        sim: null,
      },
      {
        id: 'optimistic',
        title: 'Optimistic concurrency',
        one: 'Do not lock; check at the end that nobody else changed it, and retry if they did.',
        what: [
          'Each record carries a <b>version</b>. You read the record and its version, do your work, and write back only if the version is still the one you read ("compare and swap"). If someone else got in first, your write is rejected and you start again from the new value.',
          'Nobody waits, so this is fast when conflicts are rare, which is the normal case for something like a user editing their own profile. When many writers fight over one hot record, most attempts fail and retry, and a lock would have been cheaper.',
        ],
        pros: ['No waiting and no deadlocks', 'Works across services and over HTTP, where a lock cannot be held'],
        cons: ['Wasted work and retries when conflicts are common', 'The caller must be written to retry'],
        sim: null,
      },
    ],
  },
  {
    id: 'failure',
    name: 'When things fail',
    intro: 'In a system of many machines something is always broken or slow. The design question is not how to prevent failure but what each part does when the part next to it fails.',
    topics: [
      {
        id: 'timeouts',
        title: 'Timeouts',
        one: 'Decide how long you will wait, because a slow dependency is worse than a dead one.',
        what: [
          'A dead server refuses connections at once and the caller moves on. A slow one accepts the request and then holds the caller\'s thread, memory and connection for as long as it likes. Without a <b>timeout</b>, one slow dependency spreads: its callers fill up with waiting requests, then their callers do.',
          'Choosing the value is a trade. Too long and the timeout protects nothing; too short and you abandon work the server was about to finish, which it then finishes anyway for nobody. A good timeout sits just above the slowest response you consider normal, and every hop\'s timeout is shorter than its caller\'s.',
        ],
        pros: ['Stops one slow component from stalling everything upstream', 'Turns an open-ended hang into a failure you can handle'],
        cons: ['A timed-out request may still have succeeded: you do not know', 'The abandoned work still loads the server'],
        sim: 'Under Reliability, lower the client timeout to 0.5 s while the application servers are near their limit. Requests that would have succeeded slowly now count as errors, and the "timed out (work wasted)" figure shows the server still doing them.',
      },
      {
        id: 'retries',
        title: 'Retries, backoff and jitter',
        one: 'Trying again fixes a blip and worsens an overload.',
        what: [
          'Many failures are momentary, so retrying is the cheapest reliability there is. The danger is that a struggling server now receives its normal load <i>plus</i> the retries of everything it just failed. That extra load causes more failures, which cause more retries: a <b>retry storm</b>. The system can stay down long after the original cause has gone.',
          'Three habits make retries safe. <b>Exponential backoff</b>: wait longer after each failure. <b>Jitter</b>: randomise the wait, so a thousand clients do not all return in the same instant. A <b>retry budget</b>: allow retries only up to a small fraction of normal traffic, so the amplification is bounded whatever happens.',
        ],
        pros: ['Hides brief failures from the user completely', 'Cheap to add'],
        cons: ['Multiplies load on a server that is already failing', 'Only safe if the operation can be repeated: see idempotency', 'Retries at every layer multiply each other'],
        sim: 'Under Reliability, set retries to Naive and press Traffic spike. Offered load jumps to about 4 times the real traffic and stays there after the spike has passed. Repeat with "Backoff + budget": the same spike is over in seconds.',
      },
      {
        id: 'idempotency',
        title: 'Idempotency',
        one: 'Doing it twice has the same effect as doing it once.',
        what: [
          'A request times out. Did the payment go through? The client cannot know, and the only way to make progress is to send it again. If the operation is <b>idempotent</b> that is safe; if it is not, the customer is charged twice. Since timeouts, retries and at-least-once queues all cause repeats, every operation that changes something needs an answer to "what if this arrives twice?".',
          'Some operations are idempotent by nature: "set the status to shipped" can be applied any number of times, where "add 1 to the count" cannot. The general technique is an <b>idempotency key</b>: the client generates a unique id for the operation and sends it with every attempt; the server records the id with the result, and on seeing it again returns the stored result instead of acting.',
        ],
        pros: ['Retries, redelivered messages and double-clicks all become harmless', 'The client can retry without knowing what happened'],
        cons: ['The server must store keys and results, and decide how long to keep them', 'The check and the action must happen together, or two copies arriving at once both pass'],
        sim: 'Not modelled directly, but it is the reason the queue cards say "handlers must tolerate duplicates". SQS, Pub/Sub and a worker that crashes mid-job all deliver the same job a second time.',
      },
      {
        id: 'delivery',
        title: 'Delivery guarantees',
        one: 'At most once, at least once, or the expensive illusion of exactly once.',
        what: [
          'A consumer takes a message, processes it and acknowledges it. If it crashes between processing and acknowledging, the broker cannot tell whether the work was done. It has two choices. Never redeliver, and the message may be lost: <b>at most once</b>. Redeliver, and the work may be done twice: <b>at least once</b>.',
          '<b>Exactly once</b> delivery over a network is not possible. What systems offer under that name is at-least-once delivery combined with idempotent or transactional processing, so that the duplicate has no effect. In practice: choose at least once, and make the handler idempotent.',
        ],
        pros: ['At least once never loses work', 'At most once is the simplest and fastest'],
        cons: ['At least once produces duplicates the handler must absorb', 'At most once silently drops work when a consumer dies', 'Ordering is usually lost on redelivery'],
        sim: 'Zoom into the job queue and choose "Queue internals". Each consumer holds a job that is delivered but not yet acknowledged. Kill the workers: those are the jobs a real broker would hand out again when they return.',
      },
      {
        id: 'breakers',
        title: 'Circuit breakers',
        one: 'Stop calling something that is failing, to give it room to recover.',
        what: [
          'A <b>circuit breaker</b> watches the calls to one dependency. When too many fail it "opens": further calls fail immediately without being sent. After a pause it lets a few through as a test, and closes again if they succeed.',
          'This protects both sides. The caller stops tying up threads on calls that will time out, and the failing service stops receiving traffic it cannot handle. It is most useful with a <b>fallback</b>: serve a cached or default answer while the breaker is open, so the user sees a degraded page instead of an error.',
        ],
        pros: ['Failing fast frees the caller\'s threads at once', 'Takes load off a struggling dependency so it can recover'],
        cons: ['Thresholds need tuning: too sensitive and it trips on noise', 'Without a fallback it only changes a slow error into a fast one'],
        sim: 'Not modelled. The nearest thing here is the retry budget, which also limits how much extra load a failing system is sent.',
      },
    ],
  },
  {
    id: 'load',
    name: 'Handling load',
    intro: 'Every component has a rate at which it can work. These are the ways a system behaves when asked for more than that, and the ways to raise the limit.',
    topics: [
      {
        id: 'backpressure',
        title: 'Backpressure and load shedding',
        one: 'When you cannot keep up, say so early instead of queueing without limit.',
        what: [
          'A server that receives more than it can process has three options: queue the excess, slow the sender down, or refuse it. An unbounded queue is the default and the worst. Latency grows with the queue until every request has waited so long that its client has given up, and the server is busy working on requests nobody wants.',
          '<b>Backpressure</b> pushes the limit back to the source: a full queue blocks or rejects the producer, which must then slow down. <b>Load shedding</b> rejects the excess immediately (HTTP 429 or 503) so that the requests which are accepted stay fast. Serving 80% of users well beats serving 100% of them a timeout.',
        ],
        pros: ['Latency stays bounded for the work that is accepted', 'An overload stays an overload instead of becoming a crash'],
        cons: ['Some requests are refused on purpose', 'Callers must handle rejection sensibly, not retry at once'],
        sim: 'Push traffic past what the application servers can take. On EC2 the request queue fills, memory climbs and the process is killed. Switch the technology to AWS Lambda: it sheds the excess with 429s and never falls over.',
      },
      {
        id: 'ratelimit',
        title: 'Rate limiting',
        one: 'A cap on how much any one caller may ask for.',
        what: [
          'Load shedding protects a server from the total; a <b>rate limit</b> protects everyone from one caller: a buggy client in a loop, a scraper, a customer running a batch job. Each caller gets an allowance, commonly a <b>token bucket</b> that refills at a steady rate and allows short bursts, and requests beyond it are rejected.',
          'With many servers the counts have to live somewhere shared, usually an in-memory store, or be divided approximately between servers. The limit is also a product decision: it is how a shared service promises one tenant that another cannot starve it.',
        ],
        pros: ['One misbehaving client cannot take the service down', 'Makes capacity predictable and fair between tenants'],
        cons: ['Shared counters add a lookup to every request', 'Legitimate bursts are rejected too', 'Limits set too low are an outage you caused yourself'],
        sim: 'Switch the OLTP database to DynamoDB and overload it. Requests above its provisioned capacity are throttled at once instead of queueing, which is a rate limit enforced by the service.',
      },
      {
        id: 'stateless',
        title: 'Statelessness and scaling out',
        one: 'If any server can handle any request, you can add servers freely.',
        what: [
          'There are two ways to get more capacity. <b>Scaling up</b> buys a bigger machine: simple, but it has a ceiling and is still one machine to lose. <b>Scaling out</b> adds more machines behind a load balancer, which works only if the servers are interchangeable.',
          'That requires the servers to be <b>stateless</b>: nothing a later request needs is kept in one server\'s memory or on its disk. Sessions, uploads and caches move to shared stores. The application tier then scales with a slider, and the hard problem moves to the place the state went: the database.',
        ],
        pros: ['Add or remove servers at any time, including automatically', 'Losing a server loses no data and no sessions'],
        cons: ['Every request pays a trip to a shared store for its state', 'The database becomes the bottleneck and the single point that matters'],
        sim: 'Add application servers and the bottleneck moves to the database. Then turn on autoscaling with the daily traffic pattern and watch the fleet follow the load, which is only possible because the servers hold no state.',
      },
      {
        id: 'stampede',
        title: 'Caching and the stampede',
        one: 'A cache hides load from the database, until the moment it stops.',
        what: [
          'The usual pattern is <b>cache-aside</b>: look in the cache; on a miss, read the database and put the answer in the cache with an expiry time. Most reads never reach the database, so it can be sized for a fraction of the real traffic. That saving is also the risk.',
          'When the cache is empty, after a restart or when a popular entry expires, every request misses at once and all of them go to the database together: a <b>stampede</b>. A database sized for the misses cannot take the full read load. Defences are to let only one request rebuild each entry while the others wait, to spread expiry times so entries do not all lapse together, and to warm a cache before it takes traffic.',
        ],
        pros: ['Removes most read load and latency for data that is read often', 'Cheap compared with scaling the database'],
        cons: ['Data can be stale for up to the expiry time', 'An empty cache can take the database down with it', 'Invalidating the right entry when data changes is hard to get right'],
        sim: 'At about 4,000 requests a second with four or more application servers, kill the cache. Every read falls through to the database, which is overwhelmed before the cache has warmed up again.',
      },
    ],
  },
  {
    id: 'consistency',
    name: 'Agreeing on the truth',
    intro: 'Once data lives on more than one machine, the copies can disagree. These ideas describe what a reader is allowed to see, and what it costs to make the copies agree.',
    topics: [
      {
        id: 'models',
        title: 'Strong and eventual consistency',
        one: 'Does every reader see the latest write, or will they agree later?',
        what: [
          'With <b>strong consistency</b> the system behaves like a single copy: once a write is acknowledged, every later read returns it. With <b>eventual consistency</b> the copies converge if writes stop, but a read may return an older value in the meantime.',
          'Eventual is faster and stays available when machines cannot reach each other, and it is fine for a like count or a product description. It is wrong for a bank balance. In between sit useful guarantees such as <b>read your own writes</b>: other users may see your change late, but you never see your own edit vanish, which is usually what people actually notice.',
        ],
        pros: ['Strong: simple to reason about, safe for money and inventory', 'Eventual: lower latency, and it keeps working when the network splits'],
        cons: ['Strong: slower writes, and unavailable when a majority cannot be reached', 'Eventual: the application must cope with stale and conflicting data'],
        sim: 'Add read replicas to the OLTP database and raise the write percentage. "Replication lag" in its live metrics is how stale a read from a replica can be.',
      },
      {
        id: 'cap',
        title: 'The CAP theorem',
        one: 'When the network splits, you choose between answering and being right.',
        what: [
          'Suppose the link between two groups of machines breaks: a <b>partition</b>. A request arrives at one side. That side can answer from what it has, and risk disagreeing with the other side: it stays <b>available</b>. Or it can refuse until the link is back: it stays <b>consistent</b>. It cannot do both. Partitions are not optional in a real network, so the choice is really between consistency and availability <i>during</i> one.',
          'The other half of the trade applies all the time, partition or not: keeping copies in agreement means waiting for them, so stronger consistency costs latency on every request. Most design decisions are made on that everyday trade, not on the rare partition.',
        ],
        pros: [],
        cons: ['Choosing consistency: some requests are refused while the network is split', 'Choosing availability: both sides accept writes that must be reconciled afterwards'],
        sim: null,
      },
      {
        id: 'consensus',
        title: 'Consensus and leader election',
        one: 'Getting a group of machines to agree on one value, even when some fail.',
        what: [
          'Many problems reduce to agreement: which node is the primary, what the configuration is, whether a transaction committed. <b>Consensus</b> protocols such as Raft and Paxos solve this with a <b>majority</b>: a decision stands once more than half the nodes have accepted it. Any two majorities overlap, so two conflicting decisions can never both be made.',
          'This is why such clusters have 3 or 5 members: 3 survive losing one, 5 survive losing two. It also explains the cost. Every decision waits for a round trip to a majority, so consensus is used for the small, critical things, such as who the leader is, and not for every piece of data.',
        ],
        pros: ['Exactly one leader, even through crashes and network splits', 'Nothing acknowledged is ever lost'],
        cons: ['Every decision waits for a majority, which adds latency', 'With fewer than a majority reachable, the cluster stops accepting writes', 'Difficult to implement correctly: use an existing system'],
        sim: 'Give the OLTP database a read replica and kill it. For about 30 seconds writes fail while a replica is promoted: that pause is a leader election. Cloud Spanner runs consensus on every write, which is why its card lists slower commits.',
      },
      {
        id: 'sagas',
        title: 'Two-phase commit and sagas',
        one: 'Two ways to make one change across several databases or services.',
        what: [
          '<b>Two-phase commit</b> asks every participant to prepare and promise it can commit, then tells them all to do so. It gives a true all-or-nothing result, but every participant holds locks while waiting, and if the coordinator fails at the wrong moment they are stuck holding them.',
          'A <b>saga</b> gives up all-or-nothing. It is a sequence of local transactions, each with a <b>compensating action</b> that undoes it: reserve the seat, charge the card, issue the ticket; if the charge fails, release the seat. Nothing is locked across services, but for a while the world is in a half-finished state that other requests can see, and every step and every undo must be idempotent.',
          'Both, and the alternatives to them (the transactional outbox, reserve-then-confirm, and designing the need away), are covered in depth under <b>Changing several systems</b>.',
        ],
        pros: ['Two-phase commit: real atomicity across systems', 'Sagas: no cross-service locks, and each service stays independent'],
        cons: ['Two-phase commit: slow, and blocks everyone if the coordinator fails', 'Sagas: intermediate states are visible, and some actions cannot truly be undone'],
        sim: 'Not modelled directly. Its cost shows in the sharding model, where 5% of writes are assumed to touch two shards and cost more.',
      },
      {
        id: 'clocks',
        title: 'Clocks and ordering',
        one: 'Two machines never agree on the time, so "which happened first?" is a hard question.',
        what: [
          'Clocks on different machines drift apart by milliseconds or more, and can jump backwards when they are corrected. Deciding the order of two events by comparing timestamps from different machines will sometimes get it wrong. "Last write wins" by wall-clock time therefore silently discards some updates.',
          'Systems avoid depending on time. A single log, such as a Kafka partition or a database\'s write-ahead log, gives every event a position, which is an order everyone agrees on. <b>Logical clocks</b> count events instead of seconds. Where real time cannot be avoided, the uncertainty is measured and waited out, as Spanner does.',
        ],
        pros: ['A log gives one order that every reader agrees on'],
        cons: ['A single ordered log is also a single place every write must pass through', 'Ordering across several logs or partitions is not defined'],
        sim: 'The event stream here keeps order only within one of its three partitions, which is why its panel reports lag per partition.',
      },
    ],
  },
  {
    id: 'streams',
    name: 'Processing streams',
    intro: 'A stream processor (Flink, Spark Streaming, Kafka Streams) turns an endless flow of events into results. Three design choices decide most of its cost and correctness: how events are grouped in time, how results reach the outside world exactly once, and where the job keeps what it remembers. Two compact data structures then make the answers that would otherwise need the most memory, distinct counts and per-key frequencies, fit in kilobytes.',
    topics: [
      {
        id: 'watermarks',
        title: 'Watermarks and checkpoints',
        one: 'Two markers of progress in a stream processor. A watermark says how complete the input is; a checkpoint says where to restart after a crash.',
        what: [
          'A stream never ends, so a job that counts "views per minute" must decide when a minute is finished. Events carry the time they happened (<b>event time</b>) but arrive late and out of order: a phone that was in a tunnel uploads its 12:00 events at 12:07. A <b>watermark</b> is the processor\'s running estimate that "everything up to time T has now arrived", usually the newest event time seen minus an allowance for lateness. When the watermark passes 12:01, the 12:00 window is closed and its result is emitted.',
          'A watermark is a guess, and the allowance is the trade. Too small and events arriving after their window has closed are dropped, or force a correction to a result already published. Too large and every result waits that much longer. One quiet input also holds everything back, because the watermark can only move as fast as the slowest partition.',
          'A <b>checkpoint</b> answers a different question: what happens when the processor dies. Every so often it saves a consistent snapshot of its state (the half-built counts) together with its position in the input log. After a crash it loads the last snapshot, rewinds the input to that position and replays. Each event then affects the state exactly once, though anything already written downstream is written again unless the sink is idempotent or commits together with the checkpoint.',
          'They are independent, and a correct job needs both. Watermarks are about <b>time</b> and matter even if nothing ever fails; checkpoints are about <b>failure</b> and matter even if every event arrives in order. The words are reused elsewhere: a database checkpoint is the same idea applied to the write-ahead log, while Kafka\'s "high watermark" is something else, the last offset copied to every in-sync replica.',
        ],
        pros: ['Watermarks: results grouped by when things happened, not by when they arrived', 'Checkpoints: a crash costs a replay, not the state or the events'],
        cons: ['Watermarks: a larger lateness allowance is more complete and slower; a smaller one is faster and drops stragglers', 'Checkpoints: frequent ones slow normal processing; rare ones mean a long replay after a crash', 'Replay repeats output, so the sink has to cope with duplicates'],
        sim: 'Watermarks are not modelled: every event here arrives on time and in order. Recovery from a checkpoint is. Select the lake writer and kill it: its position in the event stream stops moving and lag builds. Restart it and it carries on from where it stopped and works the backlog off, losing nothing unless it was down for longer than the stream keeps its events.',
      },
      {
        id: 'windows',
        title: 'Tumbling or sliding windows',
        one: 'Both cut an endless stream into finite pieces. Tumbling windows do not overlap; sliding windows do, and you pay for the overlap.',
        what: [
          'You cannot sum a stream that never ends, so an aggregate is computed per <b>window</b> of time. A <b>tumbling</b> window has one setting, its size: 12:00 to 12:05, then 12:05 to 12:10. Windows touch but never overlap, so every event lands in exactly one and each result counts each event once.',
          'A <b>sliding</b> window has two: a size and a slide. "The last hour, updated every 5 minutes" is size 1 hour, slide 5 minutes. The windows overlap, so each event belongs to size ÷ slide of them, 12 in this example. That overlap is the whole trade: the answer is always "the most recent hour" instead of "the hour that ended at the last boundary", and each event is counted, stored and emitted up to 12 times over. (Some systems call this a hopping window and keep "sliding" for a window that moves with every single event.)',
          'The reason to pay is the <b>boundary problem</b>. An alert for "100 errors in 5 minutes" over tumbling windows misses a burst of 60 errors at 12:04 and 60 more at 12:06: neither window reaches 100, though 120 errors arrived inside two minutes. A sliding window with a 1-minute slide catches it. The finer the slide, the less can hide between windows, and the more windows each event feeds.',
          'Two things soften the cost. For aggregates that can be combined (sums, counts, minimums and maximums) a processor can keep one small partial result per slide and merge them, instead of holding every event 12 times; that does not work for an exact median or an exact distinct count. And tumbling results add up: twelve 5-minute counts sum to an hourly count, so one cheap stream of small tumbling windows can serve many sliding views when the summing is done at query time in the analytics database. Sliding results cannot be added together, because they have already counted each event many times.',
          'A third kind, the <b>session</b> window, has no fixed size at all: it stays open while events keep arriving for a key and closes after a gap of inactivity. It fits "one user visit" and nothing with a clock on the wall.',
        ],
        versus: {
          a: 'Tumbling',
          b: 'Sliding',
          rows: [
            ['Settings', 'Size', 'Size and slide'],
            ['An event belongs to', 'Exactly one window', 'Size ÷ slide windows'],
            ['A result is emitted', 'Once per window', 'Once per slide: fresher, and that many more rows'],
            ['State and work per event', '1×', 'Up to size ÷ slide ×, unless partial results can be merged'],
            ['A burst across a boundary', 'Split in two and can go unnoticed', 'Caught, to the precision of the slide'],
            ['One late event', 'Corrects one result', 'Corrects every window it belongs to'],
            ['Results can be added up later', 'Yes: small windows roll up into large ones', 'No: every event is already counted several times'],
          ],
        },
        choose: [
          '<b>Tumbling</b> for reporting, billing periods and anything written to a database to be summed again later. It is the default: cheapest, and the only one whose results roll up.',
          '<b>Sliding</b> for alerts, rate limits, moving averages and "trending now", where the question is always about the most recent stretch of time and a missed burst matters.',
          '<b>Both at once</b>: emit small tumbling windows from the stream and compute the sliding view when it is queried. This is the usual design when an analytics database sits downstream.',
        ],
        pros: ['Tumbling: each event counted once, least state, results that add up', 'Sliding: no blind spot at window boundaries, and a result that is always current'],
        cons: ['Tumbling: a burst that straddles a boundary is diluted, and results are only as fresh as the window is long', 'Sliding: state, computation and output multiplied by size ÷ slide', 'Either: a long window with many keys is a lot of state to hold, which is the next two topics\' problem'],
        sim: 'Windowing in the lake writer is not modelled. The SLO tile in the header is a sliding window built the cheap way: it keeps 60 one-second tumbling buckets and reports their sum, so it is always "the last 60 seconds" while storing 60 numbers, not every request.',
      },
      {
        id: 'exactlyonce',
        title: 'Two-phase commit or an idempotent sink',
        one: 'Two ways to make a replay harmless to the outside world: publish nothing until it is final, or publish at once in a form that can be safely repeated.',
        what: [
          'After a crash a stream processor restores its last checkpoint and replays the input from there. Inside the job that is exactly-once. Outside it is not: whatever was written to the sink between that checkpoint and the crash is written again. The sink has to be designed for this, and there are two designs.',
          'A <b>two-phase commit sink</b> ties the output to the checkpoint. While the job runs, output goes into an open transaction that readers cannot see. When a checkpoint is taken the transaction is <i>prepared</i> (flushed and made durable, still invisible); when the checkpoint is confirmed complete it is <i>committed</i>. A crash before the checkpoint aborts the transaction, and the replay produces that output again in a new one. Nothing is ever visible twice, because nothing is visible until the checkpoint that covers it is safe.',
          'The price is latency and fragility. Output appears in steps, one per checkpoint, so results are as stale as the checkpoint interval and readers must be told to ignore uncommitted data. The sink must support transactions that outlive the process that opened them, since the job may crash after the checkpoint and has to finish the commit when it restarts. And the sink\'s transaction timeout must be longer than a checkpoint interval plus the longest outage: if a prepared transaction expires while the job is down, that output is gone although the checkpoint says it was delivered. This is data loss, not duplication, and it is the failure people forget.',
          'An <b>idempotent sink</b> gives up on hiding the duplicates and makes them harmless instead. Output is written straight away, at least once, and every record carries a key that comes out the same on replay, for example the grouping key plus the window\'s start time. The store keeps one row per key, so writing it again overwrites it with the same value. No transactions, no waiting for a checkpoint.',
          'Its price is determinism and a brief inconsistency. The replay must produce the same keys and the same values, so nothing in the output may depend on the wall clock, a random ID or the order in which unrelated events happened to arrive. It only works where a record has a natural key: an upsert of "count for this key and window" does, an append to a log or an email to a customer does not. And while a replay is in progress, a reader can see a result move backwards to an older value and then catch up again, because the earlier writes are being redone in order.',
          'File and table-format sinks are a quiet third case that behaves like two-phase commit: data files are written as the job runs, and the list of new files is committed to the table in one atomic step at each checkpoint. That is why the checkpoint interval of a job writing to a data lake decides both how fresh the table is and how many small files it accumulates.',
        ],
        versus: {
          a: 'Two-phase commit sink',
          b: 'Idempotent sink',
          rows: [
            ['The guarantee comes from', 'The sink\'s transactions, tied to checkpoints', 'Deterministic keys and a store that keeps one row per key'],
            ['Output becomes visible', 'At each checkpoint: as stale as the interval', 'At once'],
            ['The sink must support', 'Transactions that survive a restart and can be committed later', 'Upsert or deduplication by key'],
            ['The job must be', 'Anything: appends and unkeyed output are fine', 'Deterministic: the same input gives the same keys and values'],
            ['During recovery, readers see', 'Nothing new until the next commit', 'Values briefly going back, then catching up'],
            ['Its own way to lose data', 'A prepared transaction that times out during a long outage', 'A key that differs on replay, leaving both rows'],
            ['Typical sinks', 'Kafka, files and table formats, some relational databases', 'Key-value stores, a table with a primary key, a deduplicating analytics table'],
          ],
        },
        choose: [
          '<b>Two-phase commit</b> when the sink offers it and readers can wait one checkpoint interval: stream to stream through Kafka, or files into a data lake. It is also the only choice for output with no natural key.',
          '<b>Idempotent writes</b> when results must be visible in seconds or the sink has no suitable transactions, and every result has a key that survives replay. Keyed aggregates almost always do.',
          '<b>Neither fits</b> (an email, a payment): record an ID for each effect and have the receiving side refuse repeats. That is the idempotency key from "When things fail", applied at the edge of the stream.',
        ],
        pros: ['Two-phase commit: exactly-once output for any shape of data, with nothing to reconcile', 'Idempotent sink: low latency, no transactions, works with almost any store'],
        cons: ['Two-phase commit: output delayed to the checkpoint, and a timeout during an outage loses data', 'Idempotent sink: demands deterministic output and a natural key, and shows stale values while replaying', 'Either: shortening the checkpoint interval to get fresher output makes checkpoints, and small files, more frequent'],
        sim: 'Select the lake writer and switch its technology between Apache Flink and Spark Streaming. Flink commits to the lake every second, so the data is fresh and the lake fills with small files; Spark commits larger batches less often. That is the checkpoint-interval side of this trade. Deduplication at the sink is not modelled.',
      },
      {
        id: 'statebackend',
        title: 'Where the state lives',
        one: 'A streaming job remembers things between events. Keeping that memory as objects in RAM is fastest; keeping it in an embedded store on local disk lets it grow far past RAM.',
        what: [
          'Counting per key, joining two streams and holding a window open all need <b>state</b>: every count so far, every unmatched event, every open window. For a job with millions of keys and hour-long windows this is the largest thing in the system, and where it is kept decides how fast each event is handled, how big the state may grow and how long a checkpoint takes. In Flink the choice is called the state backend; Kafka Streams and Spark offer the same options under other names.',
          'The <b>in-memory</b> backend keeps state as ordinary objects on the JVM heap. Reading or updating it is a pointer lookup, with nothing to serialise, so it is the fastest option by a wide margin. The limits follow from the same fact. State cannot exceed memory. A large heap full of long-lived objects makes garbage-collection pauses long and unpredictable, and a pause stalls the whole pipeline. And each checkpoint writes out all of the state, so checkpoint time grows with state size even when little has changed.',
          'The <b>embedded store</b> backend (RocksDB) keeps state as serialised bytes in a log-structured store on the machine\'s local disk, outside the heap. State is limited by disk, not memory, so hundreds of gigabytes per machine are routine. Checkpoints can be <b>incremental</b>: only the files written since the last one are uploaded, so a checkpoint of a huge state that changed a little is quick. The price is paid on every access, which now serialises or deserialises the value and may read from disk: up to ten times slower per operation, and worse for one large value, such as a whole map kept in a single entry, which is read and rewritten in full to change one item.',
          'A third option is to keep state in an <b>external store</b> such as Redis or a database. Other services can then read it, and it survives the job being redeployed. But every access becomes a network call, orders of magnitude slower than local state, and the store is no longer covered by the job\'s checkpoints: after a replay it already contains the effects of events that are about to be processed again, so every update must be idempotent. Use it for results other systems need to query, not as working memory.',
          'State size is not fixed by the data alone; the earlier choices set it. A sliding window multiplies window state by size ÷ slide. A larger out-of-orderness bound on the watermark, or allowed lateness on a window, keeps window state for longer; a deduplication time-to-live keeps every ID seen within it, and runs on the wall clock, not on event time (the Flink deep dive covers why that distinction matters). A join with no time bound keeps everything for ever. It is often cheaper to shrink the state (a shorter time-to-live, a merged partial result instead of raw events, a coarser slide) than to move it to disk.',
        ],
        versus: {
          a: 'In memory (heap)',
          b: 'Embedded store on local disk (RocksDB)',
          rows: [
            ['State is held as', 'Live objects on the heap', 'Serialised bytes in files on local disk'],
            ['Each read or write', 'A pointer lookup', 'Serialise or deserialise, and possibly a disk read'],
            ['State can grow to', 'What fits in memory', 'What fits on local disk'],
            ['A checkpoint writes', 'All of the state, every time', 'Only what changed since the last one'],
            ['Memory behaviour', 'Garbage-collection pauses grow with state', 'A fixed budget outside the heap, predictable'],
            ['Needs', 'Enough RAM, with headroom', 'Fast local SSDs and some tuning'],
            ['Recovery of large state', 'Limited by how much there can be', 'Slow: files must be downloaded before processing resumes'],
          ],
        },
        choose: [
          '<b>In memory</b> while the state fits comfortably, a few gigabytes per machine, and latency per event matters most. It is the right default for small jobs.',
          '<b>Embedded store</b> once state is large or growing: long windows, sliding windows, joins, many keys. Also when checkpoints of the in-memory backend have become slow enough to hold the job back.',
          '<b>External store</b> only for the results that other services must read, written idempotently, alongside one of the two above.',
        ],
        pros: ['In memory: the highest throughput and lowest latency per event', 'Embedded store: state far larger than RAM, and fast incremental checkpoints'],
        cons: ['In memory: bounded by RAM, with garbage-collection pauses and full-size checkpoints as it grows', 'Embedded store: every access pays serialisation, so the same job needs more CPU', 'Either: state lives on one machine, so changing the job\'s parallelism means redistributing it'],
        sim: null,
      },
      {
        id: 'hll',
        title: 'HyperLogLog: counting distinct things',
        one: 'How many different users, to within about 1%, in a few kilobytes, however many there are.',
        what: [
          'Counting events is easy: add one. Counting <b>distinct</b> things is not, because to know whether this user is new you must remember every user you have seen. An exact count of 100 million user IDs needs a set of 100 million entries, around a gigabyte, for one number. Per page, per country and per hour, it does not fit.',
          '<b>HyperLogLog</b> estimates the count from a pattern instead of remembering the items. Hash each item to a uniform string of bits. A hash that starts with 10 zeros is a one-in-a-thousand event, so having seen one suggests roughly a thousand distinct items have gone by. One such observation is far too noisy, so the sketch splits items into many buckets by the first few bits of the hash, keeps in each bucket only the longest run of leading zeros seen so far, and combines the buckets with a harmonic mean. The same item always hashes the same way, so seeing it again changes nothing: duplicates are ignored for free.',
          'Accuracy depends only on the number of buckets <i>m</i>: the standard error is about 1.04 ÷ √m. With 16,384 buckets, the size Redis uses, that is 0.81% in 12 KB, for counts into the billions. Quadrupling the memory halves the error.',
          'The property that makes it valuable in a pipeline is that sketches <b>merge</b>. Take the larger value of each bucket from two sketches and you have exactly the sketch of the two sets combined, with nothing counted twice. So each partition can keep its own, each minute can keep its own, and the distinct count for any hour, day or group of partitions is a merge away. Exact distinct counts cannot be added like this, since the same user may appear in several of them; that is the limit on rolling up tumbling windows described above, and a sketch removes it.',
          'What it cannot do: tell you whether a given item was seen, list the items, or remove one. Intersections ("users who did both") can only be derived indirectly, and the error grows large when the overlap is small.',
        ],
        versus: {
          a: 'Exact set',
          b: 'HyperLogLog',
          rows: [
            ['Memory', 'Grows with the number of distinct items', 'Fixed: about 12 KB for 0.81% error'],
            ['Answer', 'Exact', 'An estimate; error about 1.04 ÷ √buckets'],
            ['Seeing an item again', 'Ignored', 'Ignored'],
            ['Combining two counts', 'Union the sets: needs all the items', 'Take the larger of each bucket: exact union of the sketches'],
            ['Is X in the set?', 'Yes', 'Cannot say'],
            ['Removing an item', 'Yes', 'No'],
          ],
        },
        choose: [
          '<b>HyperLogLog</b> for unique visitors, distinct devices or distinct search terms, wherever a figure within about 1% is as good as the exact one and there are many counters.',
          '<b>An exact set</b> when the number is billed, audited or small, or when you need the members themselves.',
          'It is already in the tools: <code>PFADD</code> and <code>PFCOUNT</code> in Redis, <code>APPROX_COUNT_DISTINCT</code> in BigQuery and most warehouses, the <code>uniq</code> family in ClickHouse.',
        ],
        pros: ['Fixed, tiny memory whatever the count', 'Mergeable across partitions and time windows without double counting'],
        cons: ['An estimate, never the exact figure', 'No membership test, no listing and no deletion', 'Intersections are unreliable'],
        sim: null,
      },
      {
        id: 'cms',
        title: 'Count-Min Sketch: counting how often',
        one: 'How many times has this key appeared, in fixed memory, for any number of keys. It may say too many, and never too few.',
        what: [
          'The other counting problem is frequency per key: requests per IP address, views per video, events per customer. An exact answer is a map from key to count, which grows with the number of distinct keys. When the keys are every IP address on the internet, most seen once, the map is mostly noise that you still pay to store.',
          'A <b>Count-Min Sketch</b> is a small grid of counters, with a few rows and many columns, and one hash function per row. To record a key, hash it once per row and add one to the counter it lands on in each row. To ask for a key\'s count, look at the same counters and take the <b>smallest</b>.',
          'Different keys collide and share counters, so a counter holds the key\'s true count plus whatever else landed there. Collisions only ever add, which is why every row is an overestimate and the smallest is the best one. The answer is never below the truth.',
          'The size sets the guarantee. With <i>w</i> columns and <i>d</i> rows, the estimate is too high by at most (e ÷ w) × the total of all counts, with probability 1 − e<sup>−d</sup>. A grid of 2,719 columns and 5 rows, about 54 KB of 4-byte counters, is within 0.1% of the total count, 99% of the time. Note what the error is relative to: the <b>total</b>, not the key\'s own count. For a key that makes up 5% of traffic, an error of 0.1% of the total hardly matters. For a key seen twice it is useless.',
          'That makes it the tool for <b>heavy hitters</b>. Keep the sketch, plus a short list of the keys with the largest estimates so far, and you have the top talkers of a stream without a counter per key. It is how a hot partition key or an abusive client is found. Like HyperLogLog, two sketches of the same shape merge by adding them counter by counter, so partitions and time windows combine.',
        ],
        versus: {
          a: 'Exact map of counters',
          b: 'Count-Min Sketch',
          rows: [
            ['Memory', 'One entry per distinct key', 'Fixed: columns × rows counters'],
            ['A key\'s count', 'Exact', 'True count or higher; never lower'],
            ['Size of the error', 'None', 'A fraction of the total count, set by the width'],
            ['Frequent keys', 'Exact', 'Accurate: the error is small beside the count'],
            ['Rare keys', 'Exact', 'Unreliable: the error can exceed the count'],
            ['Listing the keys', 'Yes', 'No: it must be paired with a list of candidates'],
            ['Combining two', 'Add entry by entry: needs every key', 'Add counter by counter'],
          ],
        },
        choose: [
          '<b>Count-Min Sketch</b> to find the heavy hitters: top keys, hot partitions, clients worth rate limiting, when the key space is too large to count exactly.',
          '<b>An exact map</b> when the number of keys is modest, or when small counts matter: billing per customer is not a job for a sketch.',
          '<b>They answer different questions.</b> HyperLogLog: how many different keys? Count-Min: how often this key? A Bloom filter answers the third: have I seen this key at all?',
        ],
        pros: ['Fixed memory for any number of keys', 'Never undercounts, and is accurate where it matters: on the frequent keys', 'Mergeable across partitions and windows'],
        cons: ['Overestimates, by an amount tied to total traffic', 'Useless for rare keys', 'Cannot list keys by itself'],
        sim: null,
      },
    ],
  },
  {
    id: 'crossing',
    name: 'Changing several systems',
    intro: 'One action often has to change two things that do not share a transaction: two databases, a database and a queue, your service and a payment provider. Either both changes should happen or neither, and no single system is in a position to guarantee it.',
    topics: [
      {
        id: 'dualwrite',
        title: 'The dual-write problem',
        one: 'Write to two systems one after the other, and a crash in between leaves them disagreeing.',
        what: [
          'A service saves an order to its database and then publishes an "order created" event to a queue. If it crashes after the first step, the order exists and nobody downstream ever hears of it. Swap the steps and the failure swaps too: the event is out, and the order was never saved.',
          'No ordering of the two writes fixes this, and neither does retrying: the process that would retry is the one that died. The same shape appears whenever one action touches two systems: debit one account and credit another in a different database, charge a card and mark the order paid, update a row and invalidate a cache.',
          'Everything else under this heading is a way out. They differ in what they give up: speed and availability (two-phase commit), isolation (sagas), immediacy (the outbox), or the need for the second system at all.',
        ],
        pros: [],
        cons: ['The two systems drift apart silently: nothing fails loudly', 'Rare under normal operation, so it survives testing', 'Found weeks later as "missing" emails, shipments or ledger entries'],
        sim: 'The shape is here, though its failure is not modelled: an application server writes to the database and also puts a job on the queue, as two separate calls.',
      },
      {
        id: 'twopc',
        title: 'Two-phase commit',
        one: 'A coordinator asks every participant to promise it can commit, and only then tells them all to do it.',
        what: [
          '<b>Phase 1, prepare.</b> The coordinator sends each participant its part of the work. Each one does everything short of committing: it writes the changes to its log, takes the locks, and checks its constraints. Then it votes yes or no. A yes is a <b>promise</b>: from that moment the participant may not abort on its own, even if it crashes and restarts.',
          '<b>Phase 2, commit.</b> If every vote is yes, the coordinator records the decision "commit" durably and tells every participant, which commit and release their locks. If any vote is no, or a participant does not answer in time, the decision is "abort" and everyone rolls back.',
          'The result is real atomicity: no outcome exists in which one participant committed and another did not. The weakness is the gap between the phases. A participant that has voted yes and not yet heard the decision is <b>in doubt</b>. It cannot commit, because another participant may have voted no. It cannot abort, because the decision may have been commit. If the coordinator has crashed, it can only wait, <b>holding its locks</b>, until the coordinator comes back.',
          'The costs follow. Every transaction takes two round trips and several forced writes to disk, and is as slow as its slowest participant. It succeeds only if every participant is up, so availability is the product of all of theirs. And every participant has to implement the protocol: relational databases and some message brokers do (the XA standard), while most HTTP APIs and many NoSQL stores do not.',
          'Where it is used today is mostly <b>inside</b> one product rather than between products. Distributed SQL databases such as Spanner and CockroachDB run it between their own shards. Stream processors use it to tie a sink to their checkpoints: Flink writes to Kafka inside a Kafka transaction that it commits only when the checkpoint completes.',
        ],
        pros: ['True all-or-nothing across systems', 'Nobody sees a half-finished state', 'Application code stays simple: it looks like one transaction'],
        cons: ['Locks are held across network round trips', 'A coordinator crash at the wrong moment blocks participants until it recovers', 'Slower, and less available than any single participant', 'Every participant must support it'],
        sim: 'Not modelled directly. Its cost appears in the sharding model, where 5% of writes are assumed to touch two shards and cost more.',
      },
      {
        id: 'nonblocking',
        title: 'Three-phase commit and consensus',
        one: 'Two attempts to stop a failed coordinator from blocking everyone. Only one of them is used in practice.',
        what: [
          '<b>Three-phase commit</b> inserts a "pre-commit" step between the vote and the commit, so that participants who have lost the coordinator can work out the decision among themselves. It relies on timeouts being trustworthy: on being able to tell a dead machine from a slow network. Real networks do not allow that, and when they split, two groups of participants can reach different decisions. It is taught far more often than it is run.',
          'What real systems do instead is keep two-phase commit and remove its single point of failure. The coordinator\'s decision, and each participant\'s prepared state, are stored in a <b>consensus group</b> (Paxos or Raft) of several machines. If the coordinator dies, another replica already knows the decision and finishes the job. This is how Spanner and CockroachDB commit a transaction that spans shards.',
          'It is not free: every step of the protocol is now a replicated write, which is one reason a cross-shard transaction in such a database costs noticeably more than a single-shard one.',
        ],
        pros: ['Consensus-backed commit survives the loss of any single machine', 'Keeps real transactions across shards'],
        cons: ['Each step waits for a majority of replicas', 'Only available inside databases built this way, not between arbitrary systems'],
        sim: null,
      },
      {
        id: 'saga',
        title: 'Sagas',
        one: 'Give up all-or-nothing. Run a chain of ordinary local transactions, and undo the earlier ones if a later one fails.',
        what: [
          'A saga splits the action into steps, each a normal transaction in one service: reserve the stock, charge the card, book the courier. Every step has a <b>compensating action</b> that reverses its effect: release the stock, refund the card. If step three fails, the saga runs the compensations for steps two and one.',
          'There are two ways to drive it. In <b>orchestration</b>, one service holds the state of the saga and tells each participant what to do next; the flow is in one place and easy to follow, and that service becomes a dependency of everything. In <b>choreography</b>, each service reacts to the previous one\'s event and emits its own; nothing central exists, and the flow is spread over every service that takes part.',
          'What is lost is <b>isolation</b>. Between the first step and the last, the world is in a half-finished state that other requests can see: stock is reserved for an order that may yet be cancelled. Designs cope by making the intermediate state explicit, for example an order with status "pending" that other code knows to treat with care.',
          'Compensation is not rollback. A refund is a second, visible transaction, and some things cannot be undone at all: an email that has been sent, a parcel that has left. So put steps that can fail early and steps that cannot be undone last, and make every step and every compensation <b>idempotent</b>, because the saga will retry them.',
        ],
        pros: ['No locks held across services', 'Each service stays available and independent', 'Works with any system, including third-party APIs'],
        cons: ['Half-finished states are visible to others', 'A compensation must be written and tested for every step', 'Some actions cannot be undone', 'Harder to reason about than one transaction'],
        sim: null,
      },
      {
        id: 'outbox',
        title: 'The transactional outbox',
        one: 'Turn two writes into one. Save the event in the same database transaction as the data, and publish it afterwards.',
        what: [
          'This is the direct fix for "save to the database, then publish to a queue". The service writes its business row and a row in an <b>outbox</b> table in a single local transaction, so either both exist or neither does. A separate relay then reads the outbox and publishes each row to the broker, marking it sent.',
          'The relay can poll the table, or it can use <b>change data capture</b>: read the database\'s own replication log and turn each committed outbox row into a message. The second way adds no load to the table and loses nothing, because it reads the same log the database uses to recover.',
          'The relay may crash after publishing and before recording that it did, so a message can be published twice. Delivery is <b>at least once</b>, and consumers must be idempotent; a common way is an "inbox" table of message IDs already handled, written in the same transaction as the consumer\'s own change.',
        ],
        pros: ['Needs nothing but an ordinary database transaction', 'No event is lost, and none is published for a change that was rolled back', 'The broker can be down without failing requests'],
        cons: ['Events arrive a moment later, not instantly', 'Duplicates are possible, so consumers must deduplicate', 'One more moving part to run and monitor'],
        sim: null,
      },
      {
        id: 'tcc',
        title: 'Reserve, then confirm',
        one: 'Hold the resource for a limited time first. Confirm when everything else has succeeded; otherwise let the hold lapse.',
        what: [
          'Also called <b>try-confirm/cancel</b>. Each service offers three operations. <b>Try</b> sets a resource aside without committing to anything: hold the seat, authorise the card without capturing the money. <b>Confirm</b> turns the hold into the real thing. <b>Cancel</b> releases it.',
          'It has the shape of two-phase commit, moved into the application, with one important change: a hold <b>expires</b>. If the caller crashes between try and confirm, nobody is stuck waiting on it. The seat goes back on sale after ten minutes; the card authorisation drops off after a few days.',
          'It suits anything that is naturally reservable, which is why ticketing, hotel booking and payments all work this way. The cost is that every participant has to model the held state, and confirm has to be safe to repeat.',
        ],
        pros: ['Nothing is permanently blocked by a crash: holds time out', 'Users see an honest "held for you" state', 'Maps directly onto how payment providers already work'],
        cons: ['Every service needs try, confirm and cancel, all idempotent', 'Held resources are unavailable to others meanwhile', 'A confirm that arrives after the hold has expired must be handled'],
        sim: null,
      },
      {
        id: 'avoid',
        title: 'Not needing one',
        one: 'The cheapest distributed transaction is the one you design away.',
        what: [
          '<b>Keep what must change together in one place.</b> If two tables are always updated together, put them in the same database and use an ordinary transaction. When sharding, choose a shard key that keeps related rows on one shard, so the common transactions never cross shards.',
          '<b>Make one system the source of truth and derive the rest.</b> Write only to the database, and let the search index, the cache and the analytics store be fed from its change log. They lag by a moment and can always be rebuilt, and there is no second write to get out of step.',
          '<b>Accept a short disagreement and repair it.</b> Where a brief mismatch is tolerable, let it happen and run a <b>reconciliation</b> job that compares the two systems and fixes differences. Payment systems do this every day against their bank\'s records, whatever else they use.',
        ],
        pros: ['Nothing new to build, run or get wrong', 'Local transactions are fast and well understood'],
        cons: ['Limits how freely data can be split between services', 'Derived systems are slightly behind', 'Reconciliation finds problems after the fact, not before'],
        sim: null,
      },
      {
        id: 'choosing',
        title: 'Choosing between them',
        one: 'Start from what a half-finished state would cost, and whether every participant is yours.',
        what: [
          '<b>Can it live in one database?</b> Then use a local transaction and stop here.',
          '<b>A database and a message broker?</b> The transactional outbox, with idempotent consumers.',
          '<b>Shards or tables inside one distributed database?</b> Use its transactions. It runs two-phase commit for you, with the coordinator made fault-tolerant.',
          '<b>Several services you own, in a long-running business process?</b> A saga. Use orchestration once there are more than a few steps.',
          '<b>A scarce resource to be held while something else completes, such as a seat while the customer pays?</b> Reserve, then confirm, with an expiry.',
          '<b>A third party you cannot change, such as a payment provider?</b> You cannot make it join a transaction. Use its idempotency keys, treat it as a saga step, and reconcile.',
          '<b>Two-phase commit between separate systems</b> is the last resort: only when every participant supports it, a half-finished state is truly unacceptable, and you can live with the latency and with being as available as the least available participant.',
        ],
        pros: ['Most designs need only a local transaction, an outbox and idempotent consumers'],
        cons: ['Every option except two-phase commit exposes some intermediate state: name it in the design'],
        sim: null,
      },
    ],
  },
];
