// Content for the Flink deep dive (flinkui.js): how a job runs, where it keeps state, how a
// checkpoint and Kafka offsets fit together, and the two notions of time that are easiest to mix up.
//
// This describes Apache Flink's documented behaviour (the DataStream API of Flink 1.15 and later,
// with the KafkaSource and KafkaSink connectors). Figures given as "about" are rules of thumb.
// `sim` says where this simulator shows the idea; it is null where the simulator does not model it.

export const SECTIONS = [
  {
    id: 'job',
    name: 'How a job runs',
    intro: 'A Flink job is a pipeline of operators, each running as many parallel copies. Everything else in this guide follows from one fact: a given key is always handled by the same copy, on one thread, with its state beside it.',
    topics: [
      {
        id: 'anatomy',
        title: 'Operators, subtasks and the two kinds of process',
        one: 'One coordinator plans and supervises; many workers run the parallel copies of each step.',
        what: [
          'You write a job as a chain of steps: read from Kafka, parse, group by key, aggregate in a window, write out. Flink turns each step into an <b>operator</b> and runs it as several parallel <b>subtasks</b>; the number is the operator\'s parallelism. Steps that need no regrouping are fused into one task, so a record passes between them as an ordinary method call with nothing serialised.',
          'Two kinds of process run this. The <b>JobManager</b> schedules the subtasks, watches for failures and coordinates checkpoints; it handles no data. The <b>TaskManagers</b> are the workers: each offers a number of slots and runs subtasks in them, with their state and their network buffers.',
          'Subtasks pass records through bounded network buffers. When a downstream subtask is slow its input buffers fill, the sender has nowhere to put the next record and stops, and that propagates back to the source, which simply reads from Kafka more slowly. This is <b>backpressure</b>: nothing is dropped and nothing queues without limit inside Flink. The backlog waits in Kafka, where it shows as consumer lag.',
        ],
        pros: ['Backpressure is built in: a slow step slows the source instead of losing data', 'Chained operators exchange records with no serialisation'],
        cons: ['The JobManager is a single coordinator and needs its own high-availability setup', 'A slow subtask holds back everything upstream of it, and delays checkpoints (see Checkpoints)'],
        sim: 'The lake writer is Flink by default. Raise traffic until events arrive faster than it can take them: nothing is dropped, and the backlog appears as "Lag: lake writer" on the event stream.',
      },
      {
        id: 'keys',
        title: 'Keys, key groups and why state is local',
        one: 'keyBy sends every record with the same key to the same subtask, so that subtask can keep that key\'s state without sharing it.',
        what: [
          '<code>keyBy(userId)</code> hashes the key and routes the record to one subtask of the next operator. All records for a key therefore arrive at the same subtask, in the order that subtask receives them, and each subtask processes one record at a time on one thread. That is why keyed state needs no locks, and why reading it is a local lookup instead of a call to a database.',
          'Keys are not assigned to subtasks directly. The hash first picks one of a fixed number of <b>key groups</b>, and each subtask owns a contiguous range of them. The number of key groups is the job\'s <b>maximum parallelism</b>. When you rescale a job, whole key groups move between subtasks with their state. The maximum parallelism itself cannot be changed later without discarding the state, so it is worth setting deliberately at the start.',
          'The cost of this design is skew. If one key carries a large share of the traffic, one subtask does a large share of the work whatever the parallelism, and its backpressure slows the whole job.',
        ],
        pros: ['State access is local and lock-free', 'Rescaling moves key groups, not individual keys'],
        cons: ['A hot key overloads one subtask and cannot be spread by adding parallelism', 'Maximum parallelism is fixed for the life of the job\'s state'],
        sim: null,
      },
    ],
  },
  {
    id: 'state',
    name: 'State and its backend',
    intro: 'State is what a job remembers between records. Where it is kept, on the heap or in RocksDB, sets the job\'s speed, its size limit and the cost of every checkpoint.',
    topics: [
      {
        id: 'kinds',
        title: 'What counts as state',
        one: 'Per-key values, per-operator bookkeeping such as source offsets, and timers.',
        what: [
          '<b>Keyed state</b> belongs to the key of the record being processed: a <code>ValueState</code> holding a running count, a <code>ListState</code> of buffered events, a <code>MapState</code> of entries. Windows are keyed state too: the contents or partial aggregate of every open window, per key.',
          '<b>Operator state</b> belongs to a subtask, not to a key. The important example is the Kafka source, whose state is the offset it has reached in each partition it reads. This is how offsets end up inside a checkpoint, which the next section depends on.',
          '<b>Timers</b> are state as well. "Fire when the watermark passes the end of this window" and "clear this entry in an hour" are stored per key and survive a restart like everything else. A job with many keys and a timer per key has as many timers as keys.',
        ],
        pros: ['All three are saved by a checkpoint and restored together, consistently'],
        cons: ['State you forget to clear grows for ever: every key ever seen keeps its entry'],
        sim: null,
      },
      {
        id: 'backends',
        title: 'Heap or RocksDB',
        one: 'The heap backend keeps state as Java objects: fast and bounded by memory. The RocksDB backend keeps it as bytes on local disk: slower per access, far larger, and able to checkpoint incrementally.',
        what: [
          'The <b>heap backend</b> (<code>HashMapStateBackend</code>) stores each piece of state as a live object in a hash table on the JVM heap. Reading state returns the object; nothing is serialised until a checkpoint. It is the fastest backend. Its limits are those of the heap: state must fit in memory, a heap full of long-lived state makes garbage-collection pauses longer, and each checkpoint writes out all of the state however little changed.',
          'The <b>RocksDB backend</b> (<code>EmbeddedRocksDBStateBackend</code>) stores state in an embedded key-value store on the TaskManager\'s local disk, in native memory outside the heap. Every read and write serialises the key and the value and crosses into native code, so each access costs more: typically several times slower, up to about ten. In exchange state is limited by disk rather than memory, memory use is a fixed budget instead of a growing heap, and checkpoints can be <b>incremental</b>. RocksDB writes immutable files, so a checkpoint uploads only the files created since the previous one and refers to the rest.',
          'How you shape state matters much more on RocksDB. A <code>MapState</code> stores each entry under its own key, so reading or changing one entry touches one entry. A <code>ValueState</code> holding a whole map is read and rewritten in full to change one item. <code>ListState.add</code> appends without reading the list, but reading the list back deserialises all of it. One value cannot exceed 2 GB, and a list that grows past that fails when read.',
          'The backend is separate from <b>checkpoint storage</b>, which is where snapshots are sent: durable storage such as S3 or HDFS in production. The backend decides how working state is held on the worker; checkpoint storage decides where the copies go. Changing backend later is possible by taking a savepoint and restoring from it.',
          'One behaviour differs in a way that hides bugs. On the heap backend, changing an object you got from state changes the state, even if you never call <code>update()</code>. On RocksDB it does not, because you were handed a deserialised copy. Code that forgets <code>update()</code> works in a test on the heap and silently loses updates in production on RocksDB.',
        ],
        versus: {
          a: 'Heap (HashMapStateBackend)',
          b: 'RocksDB (EmbeddedRocksDBStateBackend)',
          rows: [
            ['Working state is', 'Java objects on the JVM heap', 'Serialised bytes in files on local disk, cached in native memory'],
            ['Each access', 'A hash lookup; no serialisation', 'Serialise the key and value and call into native code'],
            ['Largest state', 'What fits in the heap', 'What fits on local disk'],
            ['A checkpoint uploads', 'All state, every time', 'Only new files, when incremental checkpoints are on'],
            ['Memory', 'Grows with state; long garbage-collection pauses', 'A fixed managed-memory budget'],
            ['Forgetting update()', 'Appears to work', 'Loses the change'],
            ['Good shape for a collection', 'Anything', 'MapState or ListState, not one large value'],
          ],
        },
        choose: [
          '<b>Heap</b> when state is small and will stay small: a few gigabytes per TaskManager at most, with headroom. Lowest latency.',
          '<b>RocksDB</b> when state is large, grows with the number of keys, or must be kept for hours: long or sliding windows, joins, deduplication. Also when full checkpoints of the heap backend have become slow.',
          'Test on the backend you run in production. The <code>update()</code> difference and the cost of large values only show on RocksDB.',
        ],
        pros: ['Heap: highest throughput per core', 'RocksDB: state far larger than memory, incremental checkpoints, predictable memory'],
        cons: ['Heap: bounded by memory; checkpoint time and pauses grow with state', 'RocksDB: more CPU per record, needs fast local disks, and has its own tuning'],
        sim: null,
      },
    ],
  },
  {
    id: 'checkpoints',
    name: 'Checkpoints and Kafka offsets',
    intro: 'A checkpoint is one consistent picture of the whole job: every operator\'s state and the exact place in the input that state corresponds to. The Kafka offsets are part of that picture, kept by Flink, not by Kafka.',
    topics: [
      {
        id: 'barriers',
        title: 'How a checkpoint is taken',
        one: 'A marker is injected at the sources and flows through the job with the data. Each operator saves its state when the marker passes.',
        what: [
          'The difficulty is that the job is running. If each operator saved its state at some moment of its own choosing, the pieces would not fit together: a record might be counted in one operator\'s snapshot and not yet in the next one\'s. Flink does not stop the job to solve this. It sends a marker, a <b>checkpoint barrier</b>, through the stream itself.',
        ],
        steps: [
          'The JobManager\'s checkpoint coordinator starts checkpoint <i>n</i> and tells the source subtasks.',
          'Each Kafka source subtask records the offset it has reached in each of its partitions, then emits barrier <i>n</i> into its output, between two records. Everything before the barrier belongs to checkpoint <i>n</i>; everything after belongs to the next.',
          'The barrier travels downstream with the records and never overtakes them. An operator that receives barrier <i>n</i> saves its state as it is at that instant, which is exactly the state produced by every record ahead of the barrier, and passes the barrier on.',
          'An operator with several inputs waits until barrier <i>n</i> has arrived on all of them, holding back the inputs that delivered it first. This is <b>alignment</b>, and it is what makes the snapshot exact.',
          'Saving has a short synchronous part and a long asynchronous one. The operator pauses only to mark what must be saved, then carries on processing while the state is uploaded to checkpoint storage in the background.',
          'Each subtask reports to the JobManager when its upload is done. When every subtask has reported, the JobManager writes the checkpoint\'s metadata and checkpoint <i>n</i> is <b>complete</b>.',
          'Only then does the JobManager notify the operators. On this notification the Kafka source commits its offsets back to Kafka, and a transactional sink commits its output.',
        ],
        after: [
          'The result is a consistent cut: source offsets saying "the input was read up to here", and operator state that reflects exactly the records before those offsets, no more and no fewer. If any subtask fails to finish in time the whole checkpoint is discarded and the job simply continues to the next one. An incomplete checkpoint is never used.',
        ],
        pros: ['The job keeps running while it is checkpointed', 'State and input position are consistent with each other by construction'],
        cons: ['Alignment holds back fast inputs while waiting for slow ones', 'Under backpressure barriers queue behind data, so checkpoints take longer exactly when the job is struggling'],
        sim: 'The lake writer here stands in for this: it keeps its position in the event stream and resumes from it. The barrier mechanism itself is not drawn.',
      },
      {
        id: 'offsets',
        title: 'Where the Kafka offsets really live',
        one: 'In Flink\'s checkpoint. The offsets committed to Kafka are a courtesy copy for monitoring, and Flink does not read them back on recovery.',
        what: [
          'An ordinary Kafka consumer records its progress by committing offsets to Kafka under its consumer group, and resumes from them. Flink does not work this way. The source\'s offsets are operator state: they are saved in each checkpoint, together with the rest of the job\'s state. That is the whole point, since an offset stored anywhere else could not be guaranteed to match the state.',
          'When a checkpoint completes, the source also commits those offsets to Kafka. This exists so that lag dashboards and other tools that read the consumer group can see progress. It is best-effort, and it happens only once per checkpoint, so the lag such tools report moves in steps and is always at least one checkpoint interval out of date.',
          'On recovery Flink restores the offsets <b>from the checkpoint</b> and seeks to them, ignoring whatever is committed in Kafka. The committed offsets are consulted only when a job starts with no state at all, and only if it is configured to start from them rather than from the earliest or latest record.',
          'Flink also does not use Kafka\'s consumer-group balancing. It assigns partitions to its own source subtasks, so there are no group rebalances and no pause when a subtask restarts. The <code>group.id</code> is just a label for the committed offsets.',
          'Two consequences are worth remembering. Resetting the consumer group\'s offsets in Kafka does not move a running Flink job; you restore from a different checkpoint or savepoint, or start with no state. And the topic\'s retention must outlast the longest outage you intend to survive: if the job is down long enough for the checkpointed offsets to be deleted, there is nothing to seek to, and depending on configuration the job fails or silently skips to what is left.',
        ],
        versus: {
          a: 'Offsets in the Flink checkpoint',
          b: 'Offsets committed to Kafka',
          rows: [
            ['Written', 'As part of every checkpoint', 'After a checkpoint completes, best-effort'],
            ['Consistent with operator state', 'Yes, by construction', 'No guarantee'],
            ['Used on recovery', 'Always', 'Never'],
            ['Used on a start with no state', 'Not applicable', 'Only if the job is configured to start from them'],
            ['Who reads them', 'Flink', 'Lag monitors and other tools'],
          ],
        },
        pros: ['Input position and state can never disagree', 'No consumer-group rebalances'],
        cons: ['Lag shown by Kafka tools is stale by up to a checkpoint interval', 'Kafka-side offset resets have no effect on a job with state', 'Retention shorter than an outage means lost input'],
        sim: 'Select the event stream, turn off auto-restart and kill the lake writer. Lag grows toward the retention limit, and past it "Expired unread" starts counting: those are events the writer\'s saved position can no longer reach.',
      },
      {
        id: 'recovery',
        title: 'Recovery, and what "exactly once" covers',
        one: 'Restore the last complete checkpoint, rewind Kafka to its offsets, and replay. State ends up as if nothing had failed; the outside world may have seen the replayed stretch twice.',
        what: [
          'When a subtask fails, Flink restarts the affected part of the job, loads every operator\'s state from the last complete checkpoint and has the sources seek to the offsets in it. Records between that checkpoint and the failure are read and processed a second time. Because the state was rewound to the same point, each record affects the state once. This is what Flink means by exactly-once: exactly-once <b>effect on state</b>, not exactly-once processing or delivery.',
          'Output is a separate matter. Whatever a sink wrote during the replayed stretch was written before the crash and is written again after it. Closing that gap is the sink\'s job, in one of two ways. A <b>transactional sink</b> such as the Kafka sink in exactly-once mode writes into a Kafka transaction, prepares it when the barrier arrives, and commits it on the "checkpoint complete" notification; output from a failed attempt is aborted and never seen. An <b>idempotent sink</b> writes at once with keys that come out the same on replay, so the repeat overwrites itself.',
          'The transactional route has two conditions people miss. Readers downstream must set <code>isolation.level=read_committed</code>, or they will read the uncommitted output anyway; and they then see new data only once per checkpoint. And a prepared transaction must still exist when the job comes back to commit it. Kafka brokers cap transaction timeouts at 15 minutes by default. A job down for longer than the timeout loses the output of its last checkpoint, although the checkpoint records it as delivered. Raise the broker\'s cap and the producer\'s timeout above the longest outage you plan for.',
        ],
        pros: ['Internal state is exact after any failure', 'With a transactional or idempotent sink, so is the output'],
        cons: ['Recovery time is the restore plus the replay of everything since the checkpoint', 'A transactional sink makes output latency equal to the checkpoint interval', 'A transaction that times out during an outage loses data'],
        sim: 'Kill the lake writer and let it restart: it resumes from its saved position and works off the backlog, losing nothing. Duplicate output at the sink is not modelled.',
      },
      {
        id: 'tuning',
        title: 'The checkpoint interval and its companions',
        one: 'One setting trades recovery time, output latency and overhead against each other.',
        what: [
          'A <b>shorter interval</b> means less to replay after a failure, fresher output from transactional sinks and fresher lag figures. It also means more snapshots to take and upload, and for a job writing files to a data lake, a commit and a set of new files every interval: an interval of one second gives very fresh data and a great many small files.',
          'Three other settings keep checkpoints from harming the job. A <b>minimum pause</b> between checkpoints guarantees the job time to process even when checkpoints run long. A <b>timeout</b> abandons a checkpoint that is taking too long. A count of <b>tolerable failures</b> decides how many abandoned checkpoints in a row are acceptable before the job itself is failed.',
          'Slow checkpoints are usually a symptom of backpressure: barriers are stuck behind queued records, and alignment holds inputs back while it waits. <b>Unaligned checkpoints</b> let a barrier overtake the queued records and save those in-flight records as part of the checkpoint. Checkpoints then finish quickly under backpressure, at the price of larger checkpoints and more I/O. The better fix is to remove the backpressure.',
          'A <b>savepoint</b> is a checkpoint you ask for by hand, in a format meant to last: use it to upgrade the job, change its parallelism or move to a different state backend. Checkpoints are for failures; savepoints are for planned changes.',
        ],
        pros: ['Short interval: fast recovery and fresh output', 'Long interval: little overhead and fewer, larger files'],
        cons: ['Short interval: more upload work, and many small files in a lake', 'Long interval: a long replay after a failure, and stale output from transactional sinks'],
        sim: 'Select the lake writer and switch between Apache Flink and Spark Streaming, then watch the data lake\'s file count. Flink commits every second (fresh data, many small files); Spark commits larger batches less often. Turn off Iceberg compaction to see what the small files cost the lake query engine.',
      },
    ],
  },
  {
    id: 'time',
    name: 'Watermarks and state TTL',
    intro: 'Two mechanisms both look like "how long do we wait". They run on different clocks and answer different questions. A watermark decides when a result is complete. A state time-to-live decides how long something is remembered. Neither does the other\'s job.',
    topics: [
      {
        id: 'watermarks',
        title: 'What a watermark means',
        one: 'A watermark with time T is a statement flowing through the job: no more events with a timestamp of T or earlier are expected.',
        what: [
          'Every event carries the time it happened, its <b>event time</b>. Events arrive out of order, so an operator cannot tell from the events alone whether it has seen everything for 12:00 to 12:05. A <b>watermark</b> tells it. It is a special record, generated at the source and carried downstream with the data, and it measures progress in event time, not on the wall clock.',
          'The usual generator assumes bounded disorder: the watermark is the largest timestamp seen so far, minus a fixed bound. With a bound of 30 seconds, seeing an event stamped 12:05:30 moves the watermark to 12:05:00, which closes the 12:00 to 12:05 window. The bound is a bet about how far out of order events arrive. It delays every result by that much, in exchange for including events up to that late.',
          'Watermarks combine by taking the minimum. The Kafka source tracks a watermark per partition and emits the lowest; an operator with several inputs uses the lowest of them. One slow or silent partition therefore holds the whole job\'s event time still, and windows stop firing although data is flowing elsewhere. Marking a source idle after a period of silence releases it.',
          'An event whose window the watermark has already passed is <b>late</b>. By default it is dropped. A window\'s <b>allowed lateness</b> keeps the window\'s state for an extra period after it fires, so that a late event updates the result and it is emitted again; whatever receives the output must then accept corrections. Events later than that can be sent to a side output instead of vanishing.',
          'Notice what a watermark is not. It says nothing about duplicates: a second copy of an event is not late, it has the same timestamp as the first. It does not depend on the wall clock: when a job replays a day of backlog in ten minutes, the watermark advances a day in ten minutes. And it is not saved in a checkpoint: after a restore, each operator\'s watermark starts again and is rebuilt from the replayed data.',
        ],
        pros: ['Results are grouped by when things happened, and are the same whether the data is live or replayed', 'A bounded wait for stragglers instead of an unbounded one'],
        cons: ['Every result is delayed by the out-of-orderness bound', 'Events later than the bound, plus any allowed lateness, are dropped or need separate handling', 'One idle partition stalls event time for the whole job'],
        sim: 'Not modelled: every event in this simulator arrives on time and in order.',
      },
      {
        id: 'ttl',
        title: 'Deduplication and state TTL',
        one: 'To drop duplicates a job must remember what it has seen. State TTL bounds that memory, and in Flink it runs on the wall clock.',
        what: [
          'Upstream systems deliver at least once, so the same event can arrive twice: a producer retried, a service replayed its log. The standard cure is to key the stream by a unique event ID and keep one small piece of state per ID meaning "seen". If the state is absent, emit the event and set it; if it is present, drop the event.',
          'Left alone, that state holds every ID for ever. <b>State TTL</b> (time-to-live) gives each entry an expiry: it is treated as gone a fixed time after it was written. The TTL is therefore the <b>deduplication horizon</b>: a duplicate that arrives within it is caught, and one that arrives after it is accepted as new.',
          'The detail that matters: Flink\'s state TTL is measured in <b>processing time</b>, the wall clock of the machine. It is not event time, and the watermark plays no part in it. An entry written at 14:00 on the wall clock with a one-hour TTL expires at 15:00 on the wall clock, whatever timestamps the events carry and wherever the watermark stands.',
          'Sizing follows from that. The TTL must exceed the longest gap, in real time, between two copies of the same event: the upstream retry window, or the furthest back an upstream replay can reach. The state it implies is the number of distinct IDs arriving within one TTL. At 5,000 events a second and a one-hour TTL that is 18 million entries; at about 100 bytes each, close to 2 GB. This is the commonest reason a simple job ends up on RocksDB.',
          'Expired entries are not removed at the instant they expire. They are hidden from reads and cleaned up in the background, on RocksDB during compaction, so disk use lags behind the TTL.',
        ],
        pros: ['Turns at-least-once input into effectively-once processing', 'A bounded, predictable amount of state'],
        cons: ['A duplicate arriving after the TTL is accepted as new', 'State is proportional to event rate × TTL', 'Wall-clock expiry behaves differently during an outage or a replay (see next)'],
        sim: null,
      },
      {
        id: 'clocks',
        title: 'Two clocks, two questions',
        one: 'The watermark\'s bound is about how late a different event may arrive, in event time. The TTL is about how far apart two copies of the same event may arrive, in wall-clock time.',
        what: [
          'It is tempting to treat these as one setting, "how long we wait for things", and to set the TTL equal to the out-of-orderness bound or assume one tidies up after the other. They are independent, and each of the following mistakes comes from merging them.',
          '<b>"The watermark has passed, so duplicates of that event can no longer arrive."</b> A duplicate is not late. An upstream retry ten minutes after the original carries the original\'s timestamp and ID. The watermark\'s bound of 30 seconds describes disorder among distinct events and says nothing about when a copy might turn up. The dedup horizon has to be chosen from retry and replay behaviour.',
          '<b>"The TTL equals the lateness bound, so state is cleared when the window closes."</b> Nothing connects them. The window closes when the watermark, in event time, passes its end. The TTL entry expires when the wall clock passes its deadline. On a live stream these happen at roughly related moments; that is a coincidence of running in real time.',
          '<b>A replay breaks the coincidence.</b> Reprocess a day of backlog in ten minutes: event time advances 24 hours while the wall clock advances ten minutes. A one-hour TTL now covers the whole day of events, so dedup state grows to 24 times its normal size. The results themselves are still right. Run the other way, with a throttled replay slower than real time, entries expire before events that are close in event time have arrived, and duplicates that the live job would have caught get through. A wall-clock TTL makes deduplication depend on how fast the job happens to run.',
          '<b>An outage does too.</b> State restored from a checkpoint keeps its original wall-clock deadlines. If the job was down for longer than the TTL, every dedup entry has expired by the time it restarts, and the replay that follows, which is exactly when duplicates are most likely, is deduplicated against nothing. Watermarks are unaffected by the outage, since they are rebuilt from the data.',
          'If deduplication must be tied to event time, do it explicitly: instead of a TTL, register an <b>event-time timer</b> for the event\'s timestamp plus the horizon, and clear the entry when it fires. Cleanup is then driven by the watermark, the horizon is measured in event time, and a replay at any speed gives the same answer. The price is a timer per key and state that is held until the watermark moves, so an idle partition that stalls the watermark also stalls cleanup.',
        ],
        versus: {
          a: 'Watermark (with its out-of-orderness bound)',
          b: 'State TTL (for deduplication)',
          rows: [
            ['Question it answers', 'Is this stretch of event time complete?', 'How long do I remember having seen this ID?'],
            ['Clock', 'Event time, carried in the data', 'Processing time, the machine\'s wall clock'],
            ['Protects against', 'Distinct events arriving out of order', 'The same event arriving more than once'],
            ['Set from', 'How far out of order events arrive', 'How far apart copies can arrive: retries, upstream replays'],
            ['When it passes', 'Windows fire; later events for them are late', 'The entry is forgotten; a later copy counts as new'],
            ['Too small', 'Stragglers dropped or results corrected later', 'Duplicates get through'],
            ['Too large', 'Every result waits longer', 'More state to hold'],
            ['Replaying a backlog fast', 'Unaffected: follows the data', 'Covers far more events: state balloons'],
            ['After a long outage', 'Rebuilt from the replayed data', 'Entries may all have expired'],
            ['Saved in a checkpoint', 'No', 'Yes, with wall-clock deadlines'],
          ],
        },
        choose: [
          '<b>Set the watermark bound</b> from measured disorder: how late, in event time, do the slowest ordinary events arrive? Seconds to a minute is typical.',
          '<b>Set the dedup horizon</b> from redelivery: how long after the first copy can another appear? This is often minutes to hours, and bears no relation to the first number.',
          '<b>Use a TTL</b> when duplicates are near-in-time redeliveries and the job runs live. It is one line of configuration.',
          '<b>Use event-time timers</b> when the job is also used for backfills, or its results must be reproducible on replay.',
          '<b>Use an idempotent sink</b> when the horizon you would need is too long to hold in state. Let the store collapse repeats by key instead.',
        ],
        pros: ['Kept separate, each can be sized for the problem it actually solves'],
        cons: ['Merged, either duplicates slip through after an outage or state grows without warning during a replay'],
        sim: null,
      },
    ],
  },
];
